const state={hotels:[],budget:90000,adults:2,children:0,tags:[],selected:[],sortAsc:true};
const tags=[['fishing','🎣 Рыбалка'],['pool','◌ SPA / Бассейн'],['pet_friendly','♧ С животными'],['forest','♢ В лесу'],['breakfast','☕ Завтрак включён']];
const $=s=>document.querySelector(s); const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₸';
function dates(){const start=new Date($('#checkIn').value+'T00:00:00'),end=new Date($('#checkOut').value+'T00:00:00');const list=[];const localISO=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;for(let d=new Date(start);d<end;d.setDate(d.getDate()+1))list.push(localISO(d));return list}
function nights(){return dates().length}
function renderTags(){$('#tagFilters').innerHTML=tags.map(([key,label])=>`<button class="tag ${state.tags.includes(key)?'active':''}" data-tag="${key}">${label}</button>`).join('')}
function filtered(){let days=dates();return state.hotels.filter(h=>days.length&& !days.some(d=>h.booked_dates.includes(d))&&h.price_per_night*days.length<=state.budget&&state.tags.every(t=>h.features.includes(t))).sort((a,b)=>state.sortAsc?a.price_per_night-b.price_per_night:b.price_per_night-a.price_per_night)}
function renderResults(){let ns=nights();$('#nightCount').textContent=`${ns} ${ns===1?'ночь':ns<5?'ночи':'ночей'}`;$('#budgetValue').textContent=new Intl.NumberFormat('ru-RU').format(state.budget);let results=filtered();$('#resultCount').textContent=`${results.length} ${plural(results.length,'вариант','варианта','вариантов')} · за ${ns} ${ns===1?'ночь':ns<5?'ночи':'ночей'}`;$('#hotelList').innerHTML=results.length?results.map(h=>`<article class="hotel-card"><div class="hotel-photo" style="background-image:url('${h.image_url}')"><span class="rating">★ ${h.rating}</span><span class="match">Совпадение ${h.match}%</span></div><div class="hotel-info"><div class="hotel-name-row"><strong class="hotel-name">${h.name}</strong></div><p class="location">⌖ ${h.location}</p><div class="price-row"><div><small>Итого за весь период</small><span class="total-price">${money(h.price_per_night*ns)}</span></div><button class="add-button ${state.selected.includes(h.id)?'added':''}" data-add="${h.id}">${state.selected.includes(h.id)?'✓ В сравнении':'＋ Сравнить'}</button></div></div></article>`).join(''):`<div class="empty">На эти даты и бюджет ничего не нашлось.<br>Попробуйте увеличить бюджет или убрать один из фильтров.</div>`;renderCompareBar()}
function plural(n,a,b,c){return n%10===1&&n%100!==11?a:n%10>=2&&n%10<=4&&(n%100<10||n%100>=20)?b:c}
function renderCompareBar(){let hs=state.hotels.filter(h=>state.selected.includes(h.id));let bar=$('#compareBar');bar.hidden=!hs.length;if(!hs.length)return;$('#compareAvatars').innerHTML=hs.map(h=>`<img src="${h.image_url}" alt="">`).join('');$('#compareBarTitle').textContent=hs.length<2?'Выберите ещё один вариант':'Готово к сравнению';$('#compareBarText').textContent=`${hs.length} из 4 мест выбрано`;$('#compareButton').disabled=hs.length<2;$('#compareButton').style.opacity=hs.length<2?.45:1}
function feature(h,key){return h.features.includes(key)?'<span class="yes">✓</span>':'<span class="no">—</span>'}
function renderCompare(){let hs=state.hotels.filter(h=>state.selected.includes(h.id));let ns=nights();$('#compareContent').innerHTML=`<div class="compare-summary"><p class="compare-date">${$('#checkIn').value.split('-').reverse().join('.')} — ${$('#checkOut').value.split('-').reverse().join('.')} · ${ns} ночи</p><div class="battle-scroll">${hs.map(h=>`<article class="battle-card"><div class="battle-img" style="background-image:url('${h.image_url}')"></div><div class="battle-top"><h3>${h.name}</h3><p>★ ${h.rating} · ${h.match}% совпадение</p></div></article>`).join('')}</div></div><div class="compare-table" style="--cols:${hs.length}">${row('Итоговая цена',hs,h=>`<span class="price">${money(h.price_per_night*ns)}</span>`)}${row('Локация',hs,h=>h.location)}${row('Бассейн / SPA',hs,h=>feature(h,'pool'))}${row('Баня',hs,h=>feature(h,'banya'))}${row('Завтрак',hs,h=>feature(h,'breakfast'))}${row('Можно с питомцем',hs,h=>feature(h,'pet_friendly'))}${row('Главный плюс',hs,h=>`<span class="pros">${h.plus}</span>`)}${row('Что учесть',hs,h=>`<span class="cons">${h.minus}</span>`)}</div>${winner(hs,ns)}`}
function row(label,hs,fn){return `<div class="compare-row"><div class="compare-label">${label}</div>${hs.map(h=>`<div class="compare-cell ${label==='Итоговая цена'?'price':''}">${fn(h)}</div>`).join('')}</div>`}
function winner(hs,ns){let best=[...hs].sort((a,b)=>(b.match+b.rating*2)-(a.match+a.rating*2))[0];return `<section class="winner"><p class="eyebrow">НАШ ВАЙБ-ВЫБОР</p><h3>${best.name}</h3><p>Лучший баланс впечатлений, рейтинга и соответствия вашим пожеланиям.</p></section>`}
function toast(t){let el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function updateGuests(){$('#adultsValue').textContent=state.adults;$('#childrenValue').textContent=state.children;$('#guestSummary').textContent=`${state.adults} ${plural(state.adults,'взрослый','взрослых','взрослых')}${state.children?`, ${state.children} ${plural(state.children,'ребёнок','ребёнка','детей')}`:', без детей'}`}
async function init(){state.hotels=await fetch('hotels_data.json').then(r=>r.json());renderTags();updateGuests();renderResults();}
$('#budgetRange').addEventListener('input',e=>{state.budget=+e.target.value;renderResults()});$('#checkIn').addEventListener('change',renderResults);$('#checkOut').addEventListener('change',renderResults);$('#tagFilters').addEventListener('click',e=>{let t=e.target.dataset.tag;if(!t)return;state.tags=state.tags.includes(t)?state.tags.filter(x=>x!==t):[...state.tags,t];renderTags();renderResults()});$('#hotelList').addEventListener('click',e=>{let id=e.target.dataset.add;if(!id)return;if(state.selected.includes(id)){state.selected=state.selected.filter(x=>x!==id)}else if(state.selected.length<4){state.selected.push(id);toast('Добавили в баттл')}else toast('Можно сравнить до 4 мест');renderResults()});$('#guestButton').onclick=()=>{let p=$('#guestPopover');p.hidden=!p.hidden;$('#guestButton').setAttribute('aria-expanded',!p.hidden)};$('#guestPopover').onclick=e=>{let b=e.target.closest('button');if(!b)return;let k=b.dataset.counter;state[k]=Math.max(k==='adults'?1:0,state[k]+ +b.dataset.step);updateGuests()};$('#sortButton').onclick=()=>{state.sortAsc=!state.sortAsc;$('#sortButton').textContent=state.sortAsc?'⇅ Цена':'⇅ Дороже';renderResults()};$('#compareButton').onclick=()=>{if(state.selected.length<2)return;$('#searchView').classList.remove('active');$('#compareView').classList.add('active');$('#compareBar').hidden=true;renderCompare();window.scrollTo(0,0)};$('#backButton').onclick=()=>{$('#compareView').classList.remove('active');$('#searchView').classList.add('active');renderCompareBar()};$('#clearButton').onclick=()=>{state.selected=[];$('#compareView').classList.remove('active');$('#searchView').classList.add('active');renderResults()};init();
